### ISSUE TITLE
question on PNG001

### ISSUE THREAD

**Issue by yqtian-se** [HexHive/magma#101]
According to the patch of [PNG001](https://github.com/HexHive/magma/tree/master/targets/libpng/patches/bugs/PNG001.patch),

The fix should be 
https://github.com/HexHive/magma/blob/2374f74c26b10c70b3dffb3c24f81fee06c59cd4/targets/libpng/patches/bugs/PNG001.patch#L10-L15

and the bug should be
https://github.com/HexHive/magma/blob/2374f74c26b10c70b3dffb3c24f81fee06c59cd4/targets/libpng/patches/bugs/PNG001.patch#L17-L28

However, I cannot understand the difference between this fixing and buggy version. I think they are doing the same thing?

I checked the original bug report, [here](https://sourceforge.net/p/libpng/bugs/278/),

according to the bug report, the buggy code should be
```c
size_t row_factor =
(png_ptr->width * png_ptr->channels * (png_ptr->bit_depth > 8? 2: 1)
 + 1 + (png_ptr->interlaced? 6: 0));
```

(compared to the fix, there is no `size_t` before `png_ptr->width` and `png_ptr-> channels`)

See also here: https://github.com/ctruta/libpng/commit/8a05766cb74af05c04c53e6c9d60c13fc4d59bf2?diff=unified#

It seems this subject in magma is different from the original bug report. May I know the reason or did I misunderstood anything?

Thanks.

**Comment by hazimeh** [comment]
The bug is that for certain values, the row factor calculation overflows to 0 and is followed by a div-by-zero. The proposed fix by the authors at the time was to cast the calculation to 64-bit ints, where overflow is not possible given the bounds on the involved variables. The canaried version of the bug performs this calculation again in a temporary, and checks if the lowest 32 bits were 0. Then, the original variable receives the low 32 bits of the calculated value, reproducing the bug if it's triggered.

**Comment by yqtian-se** [comment]
I see. Thanks
