### ISSUE TITLE
Concerns about Unequal CPU Distribution in SymCC Configuration

### ISSUE THREAD

**Issue by qhjchc** [HexHive/magma#145]
Hi there,

I noticed that symcc_afl's current configuration starts up an AFL process and a concolic engine process within a single Docker container, with only one CPU assigned. 
However, I'm concerned about the potential for unreliable and unstable experimental results if the CPU time between the two processes isn't evenly distributed.

If this limited CPU issue has already been taken into account, please let me know. 
Otherwise, it may be worth considering adjusting the CPU limitation of the container to ensure equal CPU resource allocation between both processes and allocating one CPU to each process if necessary.

**Comment by adrianherrera** [comment]
This is a good observation! I'm pretty certain this hasn't been taken into account. If you have a PR that implements your solution please feel free to submit.

**Comment by hazimeh** [comment]
This decision was deliberate, in fact. Providing one fuzzer with more cores than the rest essentially multiplies its resources. To ensure fairness, all fuzzers must have access to the same number of resources.
In effect, if SymCC+AFL utilizes 2 cores, it must be compared against a configuration of, e.g., AFL which launches 2 separate fuzzers. Otherwise, you could imagine how a mega-fuzzer can claim supremacy by utilizing 32 cores to launch 32 concurrent fuzzers, while being compared to a fuzzer running in a single-core container.

**Comment by qhjchc** [comment]
Thank you very much for your kind reply and helpful suggestions. 

After considering your feedback, I have decided to allocate more CPU resources to the hybrid fuzzers, such as SymCC+AFL, to ensure that both processes have sufficient resources to operate effectively. To ensure fairness, I will also allocate the same number of CPUs for the baseline fuzzers in parallel fuzzing mode.
