### ISSUE TITLE
Who came up with the fuzzer setup?

### ISSUE THREAD

**Issue by vanhauser-thc** [HexHive/magma#15]
Why these settings for afl++?
It is not optimal.
I would have expected that we receive a message asking for recommendations instead of a not well hand picked setup.
That is not very professional or academic.
I will create a PR over the days to fix this.
You should ask the other fuzzer maintainers what they recommend too.

**Comment by hazimeh** [comment]
Apologies. We tried to mimic the setup in FuzzBench. Your input is greatly appreciated. In any case, evaluation against Magma is not meant to provide an ultimate ranking of fuzzers, but rather identify their strengths and weaknesses in order to improve them. Our initial sample report is mot meant to judge any of the evaluated fuzzers, and fuzzer developers are always welcome to provide more suitable configurations for their fuzzers. After all, we acknowledge that it's the maintainers who are most qualified for this task. We merely provided these configurations as examples for setting up Magma against different fuzzers.
Looking forward to your PR!

**Comment by hazimeh** [comment]
Resolved by #16
