### ISSUE TITLE
archive/tar failure causing openssl target not to build

### ISSUE THREAD

**Issue by anaaktge** [HexHive/magma#33]
openssl also failed to build on a clean copy of dev, although it's failing for a slightly different reason than libxml2, php, and poppler.  This looks like it might originate in the new report tooling that is landing? 

from run.sh in the terminal:
```
Building magma/afl/openssl
[2020-09-16 05:33] Failed to build magma/afl/openssl. Check build log for info.
```
from 
../log/afl_openssl_build.log

this goes on for a while 
```
tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/Metric.py to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/main.py to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/templates to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/templates/fuzzer_template.md to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/templates/library_template.md to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't add file /home/naak/magma/tools/report_df/templates/report_template.md to tar: archive/tar: missed writing 8390 bytes"
time="2020-09-16T05:33:26Z" level=error msg="Can't close tar writer: archive/tar: missed writing 8390 bytes"
Sending build context to Docker daemon  154.1MB^M^M
Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
```

**Comment by hazimeh** [comment]
Please refer to the [Troubleshooting section](https://hexhive.epfl.ch/magma/docs/troubleshoot.html) on the Magma website.

The issue is that your workdir is under the `magma` root dir. Since the Dockerfile's context is the entirety of that directory (and all its recursive subdirectories), the docker image building process attempts to copy the workdir into the image context. However, while a campaign is running, files are constantly being added and deleted to the workdir, and this leads to a data race within the docker build and a use-after-free in the form of missing files.

Solution: Point the workdir in `captainrc` to some path above the `magma` root dir.
