### ISSUE TITLE
Poc extract only exp2json

### ISSUE THREAD

**Issue by andreafioraldi** [HexHive/magma#50]
Hi,
I'm trying to evaluate AFL++ without canaries (CANARY_MODE=2) and with POC_EXTRACT=1 to dedup the crashes.
There is a way to know which bug was triggered?

Looking at the monitor folders, they are empty, but the crashes/ folder of the fuzzer are not ofc and the poc/ folder in the workdir is filled with deduplicated testcases like "aflplusplus_openssl_asn1_NEW.uv1" (what is the meaning of the extension btw?).

Now, if I want to generate an experiment report, which is the way?
If it is not possible, is the number of testcases in poc/ the number of found bugs?

Thanks for your time,
Andrea

**Comment by hazimeh** [comment]
Interesting use case, for which I had not accounted before.
The `POC_EXTRACT` flag tells `run.sh` to launch the PoC extraction script after every campaign using the same Docker image.
But since the image was built without canaries, then the PoC extraction script will not find any ground-truth bugs, and would report all crashes as `NEW` (so, without de-duplication, essentially). I'll mark this as a bug.
That's also the reason why the `monitor/` directory is empty, but that is expected.

It is still possible, however, to get the PoCs after having finished the campaigns. Simply change the `CANARY_MODE` back to 0 and run `post_extract.sh`. I believe this will rebuild the images with canaries (if it doesn't, then just delete the old images to force Docker to recognize the need for a rebuild). Then, it'll run the extraction script on the archived campaigns.

As for the extension: since multiple crashes within the same campaign can map to the same bug, and since multiple instances of the PoC extraction script can run at the same time, I just added a random file name suffix to reduce collisions. I think this can be easily modified to use the file contents checksum for a more collision-free approach, without having to synchronize between the different running instances of the script. I'll mark this as an enhancement.

Finally, report generation requires the presence of canaries, to get time-to-bug measurements.

**Comment by hazimeh** [comment]
Keep in mind that, in the absence of canaries and ISan, some bugs may be triggered without causing a crash, and will not be saved in the output directory of AFL++. This will make the bugs in the PoCs a subset of the total set of bugs triggered by the fuzzer.

**Comment by andreafioraldi** [comment]
> This will make the bugs in the PoCs a subset of the total set of bugs triggered by the fuzzer.

Yes but on real targets u don't have canaries, I'm interested in evaluating the detection capabilities too.

So to do that I shoud (correct me if it is wrong):
1. run the campaign withiut canaries
2. compile again with canaries
3. run poc extract

As I'm using captain, how can I do just the single steps 2 and 3 without running another campaign?

**Comment by hazimeh** [comment]
As I said, `post_extract.sh` does that for you.
After having run the campaigns, modify `captainrc` to set `CANARY_MODE` to 0, then just run `./post_extract.sh` and it should take care of the rest.
Let me know if you face any problems.
