### ISSUE TITLE
interpreting bug survival graphs

### ISSUE THREAD

**Issue by wideglide** [HexHive/magma#52]
This is a graph from the [libpng](https://hexhive.epfl.ch/magma/reports/sample_2/targets/libpng.html) report.  I'm not exactly sure what information is depicted.  Was this bug ever found?  Other bugs (AAH002) don't have a graph, so I assume they were never found by any fuzzer, but this graph has symcc extended to 1w, but always 100% survival.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/558033/103683143-cf15e600-4f57-11eb-94d0-2d9192280082.png">

**Comment by adrianherrera** [comment]
Hi Josh,

This is probably explained more clearly in Fig. 5 of the paper (https://arxiv.org/pdf/2009.01120.pdf): the dotted line represents the mean __reached__ time, and the solid line represents the mean __triggered__ time. In this case, it looks as if the bug is reached by a number of fuzzers in a matter of seconds (dotted line), but is never triggered, even after 1 week (solid line).

You're probably right: the online report—in addition to the legend for each fuzzer—should say what the dotted vs. solid lines correspond to.

I hope that clears things up! Please let me know if it doesn't.

**Comment by wideglide** [comment]
Thanks for the clarification!  I was confused why AAH005 is shown in the reports and AAH002 is not shown, but I guess it is because AAH005 was reached (but never triggered), and AAH002 was never reached?  This is also confusing because it appears that AAH011 was never reached or triggered but it has a graph in the bug reports.  In this case, I think the graph is just not showing a reached time of zero?

Are you planning to release any of the raw data?

**Comment by adrianherrera** [comment]
Raw data is available here: https://osf.io/resj8/
