### ISSUE TITLE
Program name of the bugs

### ISSUE THREAD

**Issue by scanakci** [HexHive/magma#53]
Hi,

Thank you for open-sourcing this excellent fuzzing benchmark. I had a chance to run magma with different fuzzers and could trigger bugs for bunch of programs. One unclear thing in your documentation is related to the program names for specific bugs. You group bugs under libraries (e.g.. php has 16 bugs). However, most of the libraries have multiple programs and it would be good to provide the name of the program for each bug under the library (https://hexhive.epfl.ch/magma/docs/bugs.html). When I want to test a specific bug, I would be able to provide the specific program for that bug instead of fuzzing every single program in the library. Sorry this info is already documented somewhere in MAGMA. Unfortunately, I could not find after spending a good amount of time.

 Sadullah

**Comment by adrianherrera** [comment]
Hi Sadullah,

This is a good suggestion, and we can probably do this based on previous results. However, in general, deciding on the correct sequence of API calls that a library needs to call to (a) maximize code coverage and (b) uncover bugs is an open problem (see [FuzzGen](https://www.usenix.org/system/files/sec20-ispoglou.pdf) and [FUDGE](https://research.google/pubs/pub48314/)).

Leave it with me!

~Adrian

**Comment by hazimeh** [comment]
The reason is that we do not perform a reachability/triggerability study over the execution drivers of each target.
Bugs are injected in the core code base of every target, and different execution drivers may exercise different code paths in the target. Some may trigger a bug, some may reach a bug but never satisfy the condition to trigger it, and some may never exercise a code path leading to a bug.
As such, documenting which program corresponds to which bug is currently not feasible and is outside the scope of the benchmark.

For an idea on which program triggers which bug, you could check out the PoC dumps which encode the execution driver's name in the PoC's filename.
