### ISSUE TITLE
aflplusplus failed to fuzz binaries in persistent mode.

### ISSUE THREAD

**Issue by shao-hua-li** [HexHive/magma#89]
Hi there,

When I evaluated aflplusplus on Magma, I found that it would always find 0 bugs in any persistent-mode binaries. I checked the generated logs and found that fuzzing states remained unchanged. I attached one log file for libpng.

Thanks,
Shaohua

[aflplusplus_libpng_libpng_read_fuzzer_0_container.log](https://github.com/HexHive/magma/files/7163037/aflplusplus_libpng_libpng_read_fuzzer_0_container.log)

**Comment by adrianherrera** [comment]
Hey @shao-hua-li ,

Thanks for reporting this! I can confirm that I get the same results (also for `aflplusplus_lto`, and I assume the other variants): the bitmap does not fill when running AFL++ with a target linked with the [aflpp_driver](https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/aflpp_driver).

It seems like something changed in the AFL++ version used in Magma v1.1 and Magma v1.2; this problem does not occur in Magma v1.1.

I suspect the reason is because we are not doing [shared memory fuzzing](https://github.com/AFLplusplus/AFLplusplus/blob/stable/instrumentation/README.persistent_mode.md#5-shared-memory-fuzzing).

For now this can be fixed by adding either `-` or `@@` after `$ARGS` [here](https://github.com/HexHive/magma/blob/v1.2/fuzzers/aflplusplus_lto/run.sh#L26). However, I will defer to @vanhauser-thc and the AFL++ devs on the best way to fix this (to maximize AFL++ performance)?

**Comment by vanhauser-thc** [comment]
can I have a link to the file where targets are built with afl++ so I can check this out? I am not familiar with magma and have little time :(

**Comment by adrianherrera** [comment]
Hey @vanhauser-thc,

Targets are built [here](https://github.com/HexHive/magma/blob/v1.2/fuzzers/aflplusplus_lto/instrument.sh).

**Comment by vanhauser-thc** [comment]
@adrianherrera 
looking at https://github.com/HexHive/magma/blob/40ac87cd9d441de8898740276f97a1962c2a9681/fuzzers/aflplusplus_lto/fetch.sh#L32 this seems to be your own fault :)

**Comment by vanhauser-thc** [comment]
I think all the patching in this file can be removed and it should work, the main() etc. conflicts should be gone for a long time now.

**Comment by hazimeh** [comment]
The sharedmem_fuzzing global directive was disabled since the build script (of the fuzzer) would use the same driver for linking both persistent and non-persistent targets (e.g. sample tools like pdf2ppm). So instead of modifying the build scripts of the targets, the quick solution at the time was a blanket disabling of shared memory fuzzing (and just using stdin or @@ as the input vector). That is also how the persistent targets were expected to function (since the AFL driver allowed consumption of data from stdin, IIRC, when the target was called with no arguments)

I will check again whether this is still the case.

**Comment by adrianherrera** [comment]
@vanhauser-thc aaaah, I didn't think to look at the fetch script :) Thanks for pointing that out.
@hazimeh thanks for the explanation!

**Comment by hazimeh** [comment]
I settled on checking if the target binary uses the weak `main` provided by the driver, or supplies its own (supposedly strong symbol) `main`. If it's the case of the former, then we use `ARGS=-` to feed the fuzzed input through stdin (which is how the driver's `main` specifies it).

Fixed in 701006d9dfa1e0366fd4181c2ef3d871a423db05.

**Comment by zhanggenex** [comment]
https://github.com/HexHive/magma/issues/89#issuecomment-921767545


> Fixed in [701006d](https://github.com/HexHive/magma/commit/701006d9dfa1e0366fd4181c2ef3d871a423db05).

I would suggest merging this change to the main branch.

using the current main branch cannot produce the monitor results according to my test in afl++
